import mongoose from "mongoose";

const athleteSchema = mongoose.Schema(
    {
        //id generated by database
        first:{
            type: String,
            required: true,
        },
        last:{
            type: String,
            required: true,
        },
        school:{
            type: String,
            required: true,
        },
        gender:{
            type: String,
            required: true,
        },
        event:{
            type: String,
            required: true,
        },
        value:{
            type: Number,
            required: true,
        },
        grade:{
            type: String,
            required: true,
        },
    }
); 

export const Athlete = mongoose.model('Athlete', athleteSchema); 